
# 网关请求地址
gateway:
  requestUrl: http://localhost:9999/user/editInfo

# Eureka配置
eureka:
  name: tc
  password: tc123
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 5 #发呆时间，即服务续约到期时间（缺省为90s）
    lease-renewal-interval-in-seconds: 5 #心跳时间，即服务续约间隔时间（缺省为30s）
    instance-id: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ip-address}:${server.port}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.name}:${eureka.password}@localhost:8642/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒