spring:
  application:
    name: springcloud-eureka
server:
  port: 8642

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 5 #?????????
  client:
    register-with-eureka: false #????????????
    fetch-registry: false #false?????????????????????
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # ??????

